import { supabase } from '../src/config/supabase';

const figmaProducts = [
  {
    name: "Aashirvaad Select Atta",
    sku: "AASH-SEL-5KG",
    barcode: "8901725181223",
    primary_category: "Atta & Rice",
    secondary_category: "Atta",
    brand: "Aashirvaad",
    company: "ITC",
    description: "100% whole wheat chakki atta with zero maida. Made from Sharbati grains.",
    short_description: "Chakki-fresh whole wheat, no maida",
    place: "Madhya Pradesh",
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    mrp: 310.0,
    price: 255.0,
    stock: 150,
    unit: "5 kg",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: true,
    best_seller: true
  },
  {
    name: "Fortune Chakki Fresh Atta",
    sku: "FORT-ATTA-10KG",
    barcode: "8906007281315",
    primary_category: "Atta & Rice",
    secondary_category: "Atta",
    brand: "Fortune",
    company: "Adani Wilmar",
    description: "100% whole wheat chakki atta. Soft rotis guaranteed.",
    short_description: "Chakki fresh flour for daily cooking",
    place: "Gujarat",
    image_url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80",
    mrp: 520.0,
    price: 430.0,
    stock: 120,
    unit: "10 kg",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Aashirvaad Multigrain Atta",
    sku: "AASH-MULTI-5KG",
    barcode: "8901725181224",
    primary_category: "Atta & Rice",
    secondary_category: "Atta",
    brand: "Aashirvaad",
    company: "ITC",
    description: "High in dietary fibre made with 6 grains for wholesome nutrition.",
    short_description: "6 grain wholesome multigrain flour",
    place: "Madhya Pradesh",
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    mrp: 365.0,
    price: 310.0,
    stock: 90,
    unit: "5 kg",
    available: true,
    is_veg: true,
    featured: false,
    todays_deal: true,
    best_seller: false
  },
  {
    name: "Pillsbury Chakki Atta",
    sku: "PILLS-ATTA-5KG",
    barcode: "8901058002315",
    primary_category: "Atta & Rice",
    secondary_category: "Atta",
    brand: "Pillsbury",
    company: "General Mills",
    description: "Traditional stone ground whole wheat atta for extra softness.",
    short_description: "Stone ground chakki atta",
    place: "Maharashtra",
    image_url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80",
    mrp: 305.0,
    price: 265.0,
    stock: 80,
    unit: "5 kg",
    available: true,
    is_veg: true,
    featured: false,
    todays_deal: false,
    best_seller: false
  },
  {
    name: "India Gate Basmati Rice",
    sku: "ING-BASM-5KG",
    barcode: "8901262070018",
    primary_category: "Atta & Rice",
    secondary_category: "Rice",
    brand: "India Gate",
    company: "KRBL",
    description: "Aged long grain premium basmati rice for royal biryanis and pulao.",
    short_description: "Aged long grain basmati rice",
    place: "Punjab",
    image_url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80",
    mrp: 640.0,
    price: 525.0,
    stock: 75,
    unit: "5 kg",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: true,
    best_seller: true
  },
  {
    name: "Tata Sampann Toor Dal",
    sku: "TATA-TOOR-1KG",
    barcode: "8901058002316",
    primary_category: "Dals & Pulses",
    secondary_category: "Toor Dal",
    brand: "Tata Sampann",
    company: "Tata Consumer Products",
    description: "Unpolished toor dal rich in natural protein with zero chemical polish.",
    short_description: "Unpolished high protein toor dal",
    place: "Maharashtra",
    image_url: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&q=80",
    mrp: 180.0,
    price: 142.0,
    stock: 140,
    unit: "1 kg",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Fortune Sunflower Oil",
    sku: "FORT-SUN-1L",
    barcode: "8906007281316",
    primary_category: "Oils & Ghee",
    secondary_category: "Sunflower Oil",
    brand: "Fortune",
    company: "Adani Wilmar",
    description: "Light and healthy refined sunflower oil enriched with Vitamin A & D.",
    short_description: "Refined sunflower cooking oil",
    place: "Gujarat",
    image_url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
    mrp: 165.0,
    price: 135.0,
    stock: 200,
    unit: "1 L",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: true,
    best_seller: true
  },
  {
    name: "Amul Pure Ghee",
    sku: "AMUL-GHEE-1L-F",
    barcode: "8901262070019",
    primary_category: "Oils & Ghee",
    secondary_category: "Ghee",
    brand: "Amul",
    company: "GCMMF",
    description: "Pure rich granular cow ghee made from fresh milk cream.",
    short_description: "Pure premium cow milk ghee",
    place: "Gujarat",
    image_url: "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=600&q=80",
    mrp: 700.0,
    price: 649.0,
    stock: 85,
    unit: "1 L",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Everest Garam Masala",
    sku: "EVE-GARAM-100G",
    barcode: "8901725181225",
    primary_category: "Spices & Masala",
    secondary_category: "Blended Spices",
    brand: "Everest",
    company: "Everest Spices",
    description: "Aromatic blend of 13 roasted whole spices for rich curries.",
    short_description: "13 roasted spices blend",
    place: "Maharashtra",
    image_url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
    mrp: 95.0,
    price: 78.0,
    stock: 250,
    unit: "100 g",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Haldiram's Bhujia Sev",
    sku: "HALD-BHUJ-400G",
    barcode: "8901725181226",
    primary_category: "Snacks",
    secondary_category: "Namkeen",
    brand: "Haldiram",
    company: "Haldiram Snacks",
    description: "Crispy spicy moth bean flour noodles seasoned with red chilli and spices.",
    short_description: "Crispy spicy tea-time namkeen",
    place: "Rajasthan",
    image_url: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&q=80",
    mrp: 130.0,
    price: 105.0,
    stock: 180,
    unit: "400 g",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Tata Tea Gold",
    sku: "TATA-TEA-500G",
    barcode: "8901058002317",
    primary_category: "Beverages",
    secondary_category: "Tea",
    brand: "Tata Tea",
    company: "Tata Consumer Products",
    description: "Exquisite blend of Assam CTC teas with gently rolled long leaves for rich aroma.",
    short_description: "Assam CTC with aroma long leaves",
    place: "Assam",
    image_url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&q=80",
    mrp: 340.0,
    price: 285.0,
    stock: 110,
    unit: "500 g",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Parle-G Gold Biscuits",
    sku: "PARLE-GOLD-1KG",
    barcode: "8901725181227",
    primary_category: "Biscuits",
    secondary_category: "Glucose Biscuits",
    brand: "Parle",
    company: "Parle Products",
    description: "Bigger, richer and crispier glucose biscuits for the whole family.",
    short_description: "Rich glucose tea biscuit pack",
    place: "Maharashtra",
    image_url: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80",
    mrp: 150.0,
    price: 120.0,
    stock: 160,
    unit: "1 kg",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Surf Excel Matic Liquid",
    sku: "SURF-MAT-2L",
    barcode: "8901725181228",
    primary_category: "Cleaning",
    secondary_category: "Detergent",
    brand: "Surf Excel",
    company: "HUL",
    description: "Superior stain removal in washing machines with 100% liquid power.",
    short_description: "Front & top load detergent liquid",
    place: "Maharashtra",
    image_url: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80",
    mrp: 460.0,
    price: 380.0,
    stock: 95,
    unit: "2 L",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Dettol Original Liquid Handwash",
    sku: "DETT-HAND-15L",
    barcode: "8901725181229",
    primary_category: "Personal Care",
    secondary_category: "Handwash",
    brand: "Dettol",
    company: "Reckitt",
    description: "Trusted 99.9% germ protection with pine fragrance and added moisturizers.",
    short_description: "Antibacterial refill handwash pouch",
    place: "Uttarakhand",
    image_url: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    mrp: 299.0,
    price: 245.0,
    stock: 130,
    unit: "1.5 L",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Nutraj California Almonds",
    sku: "NUTR-ALM-500G",
    barcode: "8901725181230",
    primary_category: "Dry Fruits",
    secondary_category: "Almonds",
    brand: "Nutraj",
    company: "VKC Nuts",
    description: "100% natural premium California badam packed with Vitamin E & antioxidants.",
    short_description: "Premium crisp whole almonds",
    place: "California",
    image_url: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&q=80",
    mrp: 450.0,
    price: 385.0,
    stock: 90,
    unit: "500 g",
    available: true,
    is_veg: true,
    featured: true,
    todays_deal: false,
    best_seller: true
  },
  {
    name: "Harpic Power Plus Cleaner",
    sku: "HARP-POW-1L",
    barcode: "8901725181231",
    primary_category: "Home & Kitchen",
    secondary_category: "Disinfectant",
    brand: "Harpic",
    company: "Reckitt",
    description: "10x better stain and limescale removal for spotless cleaning.",
    short_description: "Disinfectant deep cleaner",
    place: "Maharashtra",
    image_url: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80",
    mrp: 215.0,
    price: 180.0,
    stock: 110,
    unit: "1 L",
    available: true,
    is_veg: true,
    featured: false,
    todays_deal: false,
    best_seller: false
  },
  {
    name: "Pampers Baby Dry Diapers (L)",
    sku: "PAMP-L-64",
    barcode: "8901725181232",
    primary_category: "Baby Care",
    secondary_category: "Diapers",
    brand: "Pampers",
    company: "P&G",
    description: "All-round protection with magic gel technology for up to 12 hours absorption.",
    short_description: "64 pants pack with wetness indicator",
    place: "Maharashtra",
    image_url: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80",
    mrp: 1099.0,
    price: 899.0,
    stock: 60,
    unit: "64 pcs",
    available: true,
    is_veg: true,
    featured: false,
    todays_deal: false,
    best_seller: true
  }
];

async function seed() {
  console.log("Seeding figma products into Supabase...");
  const { data: shops } = await supabase.from('shops').select('id').limit(1);
  const shopId = shops?.[0]?.id || 'e183b9e2-463d-4d9c-80b2-d2d2b05b7591';
  console.log("Using shop_id:", shopId);

  for (const prod of figmaProducts) {
    const prodWithShop = { ...prod, shop_id: shopId };
    const { data: existing } = await supabase.from('products').select('id').eq('sku', prod.sku).single();
    if (existing) {
      const { error: updateError } = await supabase.from('products').update(prodWithShop).eq('id', existing.id);
      if (updateError) console.error("Error updating:", prod.name, updateError.message);
      else console.log("Updated:", prod.name);
    } else {
      const { error: insertError } = await supabase.from('products').insert([prodWithShop]);
      if (insertError) console.error("Error inserting:", prod.name, insertError.message);
      else console.log("Inserted:", prod.name);
    }
  }
  console.log("Done seeding products!");
  process.exit(0);
}

seed();
